# Override Klaxit remote Rubocop config
# See https://github.com/klaxit/ruby/rubocop.yml
inherit_from:
  - https://raw.githubusercontent.com/klaxit/ruby/master/rubocop.yml

AllCops:
  Exclude:
    - 'spec/**/*'

